import { buildRubric } from "./_helpers";

export const hrRecruiterRubric = buildRubric("hr-recruiter", "HR Recruiter / Talent Acquisition", "mid", ["sourcing", "assessment", "candidate-experience"], [
  { name: "Sourcing & pipeline building", weight: 25, description: "Finds candidates through diverse channels — not just job boards.",
    scoringGuide: { 1: "Posts jobs and waits.", 2: "Basic LinkedIn searches. Relies heavily on agencies.", 3: "Boolean sourcing, GitHub/Stack Overflow mining, employee referral programs. Maintains talent pools.", 4: "Creative sourcing strategies. Employer branding that generates inbound. Talent mapping for future roles.", 5: "Builds talent acquisition function from scratch. Sourcing playbooks that scale." } },
  { name: "Candidate assessment", weight: 25, description: "Evaluates candidates accurately, designs interview processes, calibrates hiring bars.",
    scoringGuide: { 1: "Relies on gut feel. No structured evaluation.", 2: "Uses basic scorecards. Doesn't calibrate across interviewers.", 3: "Structured interviews with competency-based questions. Interviewer training. Debrief facilitation.", 4: "Designs role-specific assessment processes. Statistical tracking of interview-to-performance correlation.", 5: "Builds org-wide hiring methodology. Interviewer calibration programs. Assessment innovation." } },
  { name: "Candidate experience", weight: 20, description: "Manages the candidate journey — responsiveness, communication, feedback, and employer brand.",
    scoringGuide: { 1: "Ghosts candidates. No follow-up.", 2: "Responds to candidates but slow. Generic rejections.", 3: "Timely communication. Personalized feedback. Smooth scheduling. Candidate NPS tracking.", 4: "Candidate experience as competitive advantage. Rejected candidates become brand advocates.", 5: "Defines industry-leading candidate experience. Published case studies." } },
  { name: "Stakeholder management", weight: 15, description: "Partners with hiring managers effectively. Manages expectations and pushes back when needed.",
    scoringGuide: { 1: "Order taker. Does whatever the HM says.", 2: "Communicates pipeline status but doesn't advise.", 3: "Consults on role requirements, market data, and interview design. Pushes back on unrealistic expectations.", 4: "Trusted advisor to leadership. Influences hiring strategy. Manages competing priorities across teams.", 5: "Shapes org-wide hiring philosophy. Partners with CEO/CTO on talent strategy." } },
  { name: "Data & operations", weight: 15, description: "Tracks metrics, manages ATS, and continuously improves process efficiency.",
    scoringGuide: { 1: "No metrics. Spreadsheet chaos.", 2: "Basic ATS usage. Tracks time-to-fill.", 3: "Full funnel metrics (source-of-hire, pass-through rates, offer acceptance). Process documentation.", 4: "Data-driven optimization. Identifies bottlenecks, automates where possible. Cost-per-hire analysis.", 5: "Builds TA operations function. Predictive hiring models. Automation at scale." } },
]);
